platform :ios, '9.0'

inhibit_all_warnings!

target 'AxcUIKit' do
# masonry适配
  pod 'Masonry', '~> 1.0.2'
  pod 'GPUImage'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'AFNetworking'
  pod 'ReactiveCocoa', '~> 2.5'


end
